-- FiveM for GTAV Enhanced: submix effects (MumbleSetSubmixForServerId) have no equivalent
-- in the new voice API and are no longer used anywhere in this resource. This file is kept
-- (empty) only so it doesn't 404 if something external still references the path; it is no
-- longer loaded by fxmanifest.lua's client_scripts.
